
--DROP TABLE InvoiceLines
--DROP TABLE Articles
--DROP TABLE Categories
--DROP TABLE Transactions
--DROP TABLE Snapshots
--DROP TABLE Accounts
--DROP TABLE Counterparties
--DROP TABLE Users


CREATE TABLE Users
(
	Id INT NOT NULL PRIMARY KEY,
	Name NVARCHAR(32) NOT NULL,
	Pwd NVARCHAR(16)
)

CREATE TABLE Accounts
(
	Id INT NOT NULL PRIMARY KEY,
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	Name NVARCHAR(32) NOT NULL,
	Currency NCHAR(3) NOT NULL,
	Note NVARCHAR(255)
)

CREATE TABLE Articles
(
	Id INT NOT NULL PRIMARY KEY,
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	CaterogyId INT FOREIGN KEY REFERENCES Articles(Id),
	Label NVARCHAR(32) NOT NULL,
	IsArticle BIT NOT NULL
)

CREATE TABLE Counterparties
(
	Id INT NOT NULL PRIMARY KEY,
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	IsSupplier BIT NOT NULL,
	Name NVARCHAR(32) NOT NULL,
	Note NVARCHAR(255)
)

CREATE TABLE Transactions
(
	Id INT NOT NULL PRIMARY KEY,
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	AccountId INT NOT NULL FOREIGN KEY REFERENCES Accounts(Id),
	CounterpartyId INT FOREIGN KEY REFERENCES Counterparties(Id),
	Amount INT NOT NULL,
	TransactionDate DATE NOT NULL,
	Note NVARCHAR(255)
)

CREATE TABLE InvoiceLines
(
	Id INT NOT NULL PRIMARY KEY,
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	TransactionId INT NOT NULL FOREIGN KEY REFERENCES Transactions(Id),
	ArticleId INT NOT NULL FOREIGN KEY REFERENCES Articles(Id),
	Price INT NOT NULL,
	Note NVARCHAR(255)
)

CREATE TABLE Snapshots
(
	Id INT NOT NULL PRIMARY KEY,
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	AccountId INT NOT NULL FOREIGN KEY REFERENCES Accounts(Id),
	Amount INT NOT NULL,
	SnapshotDate DATE NOT NULL,
	Note NVARCHAR(255)
)


