//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privat24Module {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Privat24Module.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;request version=&quot;1.0&quot;&gt;
        ///    &lt;merchant&gt;
        ///        &lt;id&gt;75482&lt;/id&gt;
        ///        &lt;signature&gt;5abf5c7524bc2a835acb3a9e24ce10bc5ba82a99&lt;/signature&gt;
        ///    &lt;/merchant&gt;
        ///    &lt;data&gt;
        ///        &lt;oper&gt;cmt&lt;/oper&gt;
        ///        &lt;wait&gt;0&lt;/wait&gt;
        ///        &lt;test&gt;0&lt;/test&gt;
        ///        &lt;payment id=&quot;&quot;&gt;
        ///            &lt;prop name=&quot;sd&quot; value=&quot;11.08.2013&quot; /&gt;
        ///            &lt;prop name=&quot;ed&quot; value=&quot;11.09.2013&quot; /&gt;
        ///            &lt;prop name=&quot;card&quot; value=&quot;5168742060221193&quot; /&gt;
        ///        &lt;/payment&gt;
        ///    &lt;/data&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string rest_fiz {
            get {
                return ResourceManager.GetString("rest_fiz", resourceCulture);
            }
        }
    }
}
