Use Bookkeeping

DELETE FROM [InvoiceLines]
DELETE FROM [Articles]
DELETE FROM [Transactions]
DELETE FROM [Snapshots]
DELETE FROM [Accounts]
DELETE FROM [Counterparties]
DELETE FROM [Users]

INSERT INTO [Users] (Name, Pwd)
VALUES (N'Наша сім''я', NULL)

INSERT INTO [Accounts] (UserId, IsActive, Name, Currency, Note)
VALUES (1, 'true', N'Готівка', N'ГРН', NULL)
INSERT INTO [Accounts] (UserId, IsActive, Name, Currency, Note)
VALUES (1, 'true', N'Готівка $', N'USD', NULL)
INSERT INTO [Accounts] (UserId, IsActive, Name, Currency, Note)
VALUES (1, 'true', N'Гаманець', N'ГРН', NULL)
INSERT INTO [Accounts] (UserId, IsActive, Name, Currency, Note)
VALUES (1, 'true', N'2600 Агріколь', N'ГРН', NULL)
INSERT INTO [Accounts] (UserId, IsActive, Name, Currency, Note)
VALUES (1, 'true', N'Приват', N'ГРН', NULL)
INSERT INTO [Accounts] (UserId, IsActive, Name, Currency, Note)
VALUES (1, 'true', N'Картка', N'ГРН', NULL)

INSERT INTO [Counterparties] (UserId, Name, Note)
VALUES (1, N'Cільпо', NULL)
INSERT INTO [Counterparties] (UserId, Name, Note)
VALUES (1, N'Алейка', NULL)
INSERT INTO [Counterparties] (UserId, Name, Note)
VALUES (1, N'Обмінник', NULL)
INSERT INTO [Counterparties] (UserId, Name, Note)
VALUES (1, N'Ліко-Світ', NULL)
INSERT INTO [Counterparties] (UserId, Name, Note)
VALUES (1, N'Метро', NULL)
INSERT INTO [Counterparties] (UserId, Name, Note)
VALUES (1, N'Обмінник', NULL)
INSERT INTO [Counterparties] (UserId, Name, Note)
VALUES (1, N'Твінфілд', NULL)

INSERT INTO [Transactions] (UserId, AccountId, CounterpartyId, Amount, TransactionDate, Note)
VALUES (1, 1, 1, -100, '2016-06-01', NULL)
INSERT INTO [Transactions] (UserId, AccountId, CounterpartyId, Amount, TransactionDate, Note)
VALUES (1, 1, 2, -52.3, '2016-06-01', NULL)
INSERT INTO [Transactions] (UserId, AccountId, CounterpartyId, Amount, TransactionDate, Note)
VALUES (1, 3, 3, -2500, '2016-06-01', N'25.00 грн/$')
INSERT INTO [Transactions] (UserId, AccountId, CounterpartyId, Amount, TransactionDate, Note)
VALUES (1, 2, 6, 100, '2016-06-01', NULL)
INSERT INTO [Transactions] (UserId, AccountId, CounterpartyId, Amount, TransactionDate, Note)
VALUES (1, 4, 7, 50000, '2016-06-02', NULL)
INSERT INTO [Transactions] (UserId, AccountId, CounterpartyId, Amount, TransactionDate, Note)
VALUES (1, 5, 4, -7500, '2016-06-02', N'Аванс за послуги Інтернет, червень 2016, згідно договору №2525')
INSERT INTO [Transactions] (UserId, AccountId, CounterpartyId, Amount, TransactionDate, Note)
VALUES (1, 6, 5, -65.43, '2016-06-02', NULL)
INSERT INTO [Transactions] (UserId, AccountId, CounterpartyId, Amount, TransactionDate, Note)
VALUES (1, 1, 2, 152.55, '2016-06-02', NULL)

INSERT INTO [Snapshots] (UserId, AccountId, Amount, SnapshotDate, Note)
VALUES (1, 1, 3568.95, '2016-06-01', NULL)
INSERT INTO [Snapshots] (UserId, AccountId, Amount, SnapshotDate, Note)
VALUES (1, 2, 100, '2016-06-01', NULL)
INSERT INTO [Snapshots] (UserId, AccountId, Amount, SnapshotDate, Note)
VALUES (1, 3, 2150, '2016-06-01', NULL)
INSERT INTO [Snapshots] (UserId, AccountId, Amount, SnapshotDate, Note)
VALUES (1, 4, 75000, '2016-06-01', NULL)
INSERT INTO [Snapshots] (UserId, AccountId, Amount, SnapshotDate, Note)
VALUES (1, 5, 14569, '2016-06-01', NULL)
INSERT INTO [Snapshots] (UserId, AccountId, Amount, SnapshotDate, Note)
VALUES (1, 6, 5890.85, '2016-06-01', NULL)

INSERT INTO [Articles] (UserId, CategoryId, Label, IsArticle, IsForPurchase)
VALUES (1, NULL, N'Продукти харчування', 'false', 'true')
INSERT INTO [Articles] (UserId, CategoryId, Label, IsArticle, IsForPurchase)
VALUES (1, NULL, N'Транспорт', 'false', 'true')
INSERT INTO [Articles] (UserId, CategoryId, Label, IsArticle, IsForPurchase)
VALUES (1, 1, N'Молоко', 'true', 'true')
INSERT INTO [Articles] (UserId, CategoryId, Label, IsArticle, IsForPurchase)
VALUES (1, 1, N'Хліб', 'true', 'true')
INSERT INTO [Articles] (UserId, CategoryId, Label, IsArticle, IsForPurchase)
VALUES (1, 1, N'Черешні', 'true', 'true')
INSERT INTO [Articles] (UserId, CategoryId, Label, IsArticle, IsForPurchase)
VALUES (1, 1, N'Помідори', 'true', 'true')
INSERT INTO [Articles] (UserId, CategoryId, Label, IsArticle, IsForPurchase)
VALUES (1, 1, N'Яблука', 'true', 'true')
INSERT INTO [Articles] (UserId, CategoryId, Label, IsArticle, IsForPurchase)
VALUES (1, 1, N'Ікра', 'true', 'true')
INSERT INTO [Articles] (UserId, CategoryId, Label, IsArticle, IsForPurchase)
VALUES (1, 1, N'Торт', 'true', 'true')
INSERT INTO [Articles] (UserId, CategoryId, Label, IsArticle, IsForPurchase)
VALUES (1, 1, N'Серветки', 'true', 'true')

INSERT INTO [InvoiceLines] (UserId, TransactionId, ArticleId, Price, Note)
VALUES (1, 1, 3, 10.50, NULL)
INSERT INTO [InvoiceLines] (UserId, TransactionId, ArticleId, Price, Note)
VALUES (1, 1, 4, 15.20, NULL)
INSERT INTO [InvoiceLines] (UserId, TransactionId, ArticleId, Price, Note)
VALUES (1, 1, 5, 50.50, N'60 грн/кг')
INSERT INTO [InvoiceLines] (UserId, TransactionId, ArticleId, Price, Note)
VALUES (1, 2, 6, 30.49, N'25 грн/кг')
INSERT INTO [InvoiceLines] (UserId, TransactionId, ArticleId, Price, Note)
VALUES (1, 2, 7, 25.25, N'15 грн/кг')
INSERT INTO [InvoiceLines] (UserId, TransactionId, ArticleId, Price, Note)
VALUES (1, 7, 8, 100.50, NULL)
INSERT INTO [InvoiceLines] (UserId, TransactionId, ArticleId, Price, Note)
VALUES (1, 7, 9, 150.75, NULL)
INSERT INTO [InvoiceLines] (UserId, TransactionId, ArticleId, Price, Note)
VALUES (1, 7, 10, 30.00, NULL)





